-- Auto-generated by compiler.rb - DO NOT EDIT
-- Airtight wall tile lists for ZSpaceship
-- This file is generated from the map YAML configuration

ZSRoom = ZSRoom or {}

-- Lookup tables for faster validation (O(1) instead of O(n))
-- North/South walls (getWall(true))
ZSRoom.AIRTIGHT_WALLS_NS_LOOKUP = {
    ["industry_railroad_05_25"] = true,
    ["industry_railroad_05_26"] = true,
    ["location_community_medical_01_169"] = true,
    ["location_community_medical_01_170"] = true,
    ["walls_garage_01_33"] = true,
    ["walls_garage_02_17"] = true
}

-- East/West walls (getWall(false))
ZSRoom.AIRTIGHT_WALLS_EW_LOOKUP = {
    ["industry_railroad_05_24"] = true,
    ["industry_railroad_05_26"] = true,
    ["location_community_medical_01_168"] = true,
    ["location_community_medical_01_170"] = true,
    ["walls_garage_01_32"] = true,
    ["walls_garage_02_16"] = true
}

-- Door tiles (North/South direction)
ZSRoom.AIRTIGHT_DOORS_NS_LOOKUP = {
    ["walls_garage_02_52"] = true,
    ["walls_garage_02_60"] = true
}

-- Door tiles (East/West direction)
ZSRoom.AIRTIGHT_DOORS_EW_LOOKUP = {
    ["walls_garage_02_49"] = true,
    ["walls_garage_02_57"] = true
}
