-- ZSRoom class for ZSpaceship mod
-- Represents a room with utility methods

-- ZSRoom class
ZSRoom = ZSRoom or {}
ZSRoom.__index = ZSRoom

ZSRoom.State = {
    UNKNOWN = "unknown",
    CHECKING = "checking",
    SEALED = "sealed",
    BREACHED = "breached",
}

-- Static helper: Generate string key from square coordinates
function ZSRoom.getSquareKey(sq)
    if not sq then return nil end
    local x, y, z = sq:getX(), sq:getY(), sq:getZ()
    if x and y and z then
        return x .. ":" .. y .. ":" .. z
    end
    return nil
end

-- Static helper: Generate string key from coordinates
function ZSRoom.getSquareKeyFromCoords(x, y, z)
    if x and y and z then
        return x .. ":" .. y .. ":" .. z
    end
    return nil
end

-- Static helper: Check if square is open space
function ZSRoom.isOpenSpace(sq)
    if not sq then return false end
    local x, y = sq:getX(), sq:getY()
    if ZSpaceship and ZSpaceship.isInSpace and x and y then
        if ZSpaceship.isInSpace(x, y) then return true end
    end
    local hasFloor = sq.getFloor and sq:getFloor() ~= nil
    local hasRoof = sq.getRoof and sq:getRoof() ~= nil
    return not hasFloor or not hasRoof
end

-- Whitelist of airtight wall tiles
-- These are populated by ZSpaceship_MapData.lua (generated by compiler.rb)
ZSRoom.AIRTIGHT_WALLS_NS = ZSRoom.AIRTIGHT_WALLS_NS or {}
ZSRoom.AIRTIGHT_WALLS_EW = ZSRoom.AIRTIGHT_WALLS_EW or {}

-- Constructor: create a new ZSRoom instance from a square or room object
function ZSRoom:new(squareOrRoom)
    local instance = {}
    setmetatable(instance, ZSRoom)
    
    local isoRoom = nil
    if squareOrRoom then
        if squareOrRoom.getRoom then
            -- It's a square
            isoRoom = squareOrRoom:getRoom()
        else
            -- Assume it's a isoRoom object
            isoRoom = squareOrRoom
        end
    end
    
    instance.isoRoom = isoRoom
    instance.squares = nil
    
    -- Cache properties (initialized to nil, computed on demand)
    instance.airtight = nil
    instance.connections = {}  -- { [roomId] = { door = door object, square = square, adjSquare = adjSquare } }
    instance.doors = nil  -- Cached doors list
    instance.vacuumState = nil  -- Cached vacuum breach state (true = breached, false = sealed)

    self:update()
    
    return instance
end

-- Get the room ID
function ZSRoom:getID()
    return self.isoRoom and tostring(self.isoRoom) or nil
end

-- Check if the room is valid
function ZSRoom:isValid()
    if not self.isoRoom or not self.squares then return false end
    -- Check if table has any entries
    for _ in pairs(self.squares) do
        return true
    end
    return false
end

-- Update room properties (open space, missing walls, airtight, connections)
function ZSRoom:update()
    if self.isoRoom and self.isoRoom.getSquares and self.isoRoom:getSquares():size() > 0 then
        local javaSquares = self.isoRoom:getSquares()
        -- Convert Java collection to Lua table with key = "x:y:z"
        self.squares = {}
        if javaSquares then
            for i = 0, javaSquares:size() - 1 do
                local sq = javaSquares:get(i)
                if sq then
                    local key = ZSRoom.getSquareKey(sq)
                    if key then
                        self.squares[key] = sq
                    end
                end
            end
        end
    end
    if not self:isValid() then return end
    
    self.airtight = false
    local validation = self:validate()
    self.airtight = validation and validation.allAirtight == true

    self.doors = nil -- invalidate doors cache
end

-- Get the room name
function ZSRoom:getName()
    local room = self.isoRoom
    if not room then return nil end

    local name = room.getName and room:getName() or nil
    if not name then name = tostring(room) end
    return name
end

-- Get the room object
function ZSRoom:getIsoRoom()
    return self.isoRoom
end

-- Get all squares in the room
function ZSRoom:getSquares()
    return self.squares
end

-- Get the number of squares in the room
function ZSRoom:getSquareCount()
    if not self.squares then return 0 end
    local count = 0
    for _ in pairs(self.squares) do
        count = count + 1
    end
    return count
end

-- Get the north side Y coordinate (minimum Y)
function ZSRoom:getSideY_N()
    if not self:isValid() then
        return nil
    end
    
    local minY = nil
    for _, sq in pairs(self.squares) do
        if sq then
            local y = sq:getY()
            if minY == nil or y < minY then
                minY = y
            end
        end
    end
    
    return minY
end

-- Get all squares on the north side
function ZSRoom:getSquaresN()
    if not self:isValid() then
        return {}
    end
    
    local northY = self:getSideY_N()
    if not northY then
        return {}
    end
    
    local northSquares = {}
    for _, sq in pairs(self.squares) do
        if sq and sq:getY() == northY then
            table.insert(northSquares, sq)
        end
    end
    
    return northSquares
end

-- Get the west side X coordinate (minimum X)
function ZSRoom:getSideX_W()
    if not self:isValid() then
        return nil
    end
    
    local minX = nil
    for _, sq in pairs(self.squares) do
        if sq then
            local x = sq:getX()
            if minX == nil or x < minX then
                minX = x
            end
        end
    end
    
    return minX
end

-- Get all squares on the west side
function ZSRoom:getSquaresW()
    if not self:isValid() then
        return {}
    end
    
    local westX = self:getSideX_W()
    if not westX then
        return {}
    end
    
    local westSquares = {}
    for _, sq in pairs(self.squares) do
        if sq and sq:getX() == westX then
            table.insert(westSquares, sq)
        end
    end
    
    return westSquares
end

-- Get the east side X coordinate (maximum X)
function ZSRoom:getSideX_E()
    if not self:isValid() then
        return nil
    end
    
    local maxX = nil
    for _, sq in pairs(self.squares) do
        if sq then
            local x = sq:getX()
            if maxX == nil or x > maxX then
                maxX = x
            end
        end
    end
    
    return maxX
end

-- Get all squares on the east side
function ZSRoom:getSquaresE()
    if not self:isValid() then
        return {}
    end
    
    local eastX = self:getSideX_E()
    if not eastX then
        return {}
    end
    
    local eastSquares = {}
    for _, sq in pairs(self.squares) do
        if sq and sq:getX() == eastX then
            table.insert(eastSquares, sq)
        end
    end
    
    return eastSquares
end

-- Get wall tiles on the north side
function ZSRoom:getWallsDoorsN()
    local northSquares = self:getSquaresN()
    local walls = {}
    
    for _, sq in ipairs(northSquares) do
        local x, y, z = sq:getX(), sq:getY(), sq:getZ()
        -- Check for wall on the north side of this square
        -- true = north wall
        local wall = sq:getWall(true) or sq:getDoor(true)
        if wall then
            local tileName = nil
            if wall.getSpriteName then
                tileName = wall:getSpriteName()
            elseif wall.getTile then
                tileName = wall:getTile()
            elseif wall.getName then
                tileName = wall:getName()
            end
            
            table.insert(walls, {
                square = sq,
                x = x,
                y = y,
                z = z,
                wall = wall,
                tileName = tileName
            })
        end
    end
    
    return walls
end

-- Get the south side Y coordinate (maximum Y)
function ZSRoom:getMaxY()
    if not self:isValid() then
        return nil
    end
    
    local maxY = nil
    for _, sq in pairs(self.squares) do
        if sq then
            local y = sq:getY()
            if maxY == nil or y > maxY then
                maxY = y
            end
        end
    end
    
    return maxY
end

-- Get all squares on the south side
function ZSRoom:getSquaresS()
    if not self:isValid() then
        return {}
    end
    
    local southY = self:getMaxY()
    if not southY then
        return {}
    end
    
    local southSquares = {}
    for _, sq in pairs(self.squares) do
        if sq and sq:getY() == southY then
            table.insert(southSquares, sq)
        end
    end
    
    return southSquares
end

-- Get wall tiles on the south side
function ZSRoom:getWallsDoorsS()
    local southSquares = self:getSquaresS()
    local walls = {}
    
    for _, sq in ipairs(southSquares) do
        local x, y, z = sq:getX(), sq:getY(), sq:getZ()
        -- For south walls, check the square to the south (y+1) for its north wall
        local southSq = getSquare(x, y + 1, z)
        -- north wall of south square = south wall of current
        local wall = southSq and (southSq:getWall(true) or southSq:getDoor(true))
        if wall then
            local tileName = nil
            if wall.getSpriteName then
                tileName = wall:getSpriteName()
            elseif wall.getTile then
                tileName = wall:getTile()
            elseif wall.getName then
                tileName = wall:getName()
            end
            
            table.insert(walls, {
                square = sq,
                x = x,
                y = y,
                z = z,
                wall = wall,
                tileName = tileName
            })
        end
    end
    
    return walls
end

-- Get wall tiles on the east side
function ZSRoom:getWallsDoorsE()
    local eastSquares = self:getSquaresE()
    local walls = {}
    
    for _, sq in ipairs(eastSquares) do
        local x, y, z = sq:getX(), sq:getY(), sq:getZ()
        -- For east walls, check the square to the east (x+1) for its west wall
        local eastSq = getSquare(x + 1, y, z)
        -- west wall of east square = east wall of current
        local wall = eastSq and (eastSq:getWall(false) or eastSq:getDoor(false))
        if wall then
            local tileName = nil
            if wall.getSpriteName then
                tileName = wall:getSpriteName()
            elseif wall.getTile then
                tileName = wall:getTile()
            elseif wall.getName then
                tileName = wall:getName()
            end
            
            table.insert(walls, {
                square = sq,
                x = x,
                y = y,
                z = z,
                wall = wall,
                tileName = tileName
            })
        end
    end
    
    return walls
end

-- Get wall tiles on the west side
function ZSRoom:getWallsDoorsW()
    local westSquares = self:getSquaresW()
    local walls = {}
    
    for _, sq in ipairs(westSquares) do
        local x, y, z = sq:getX(), sq:getY(), sq:getZ()
        -- false = west wall
        local wall = sq:getWall(false) or sq:getDoor(false)
        if wall then
            local tileName = nil
            if wall.getSpriteName then
                tileName = wall:getSpriteName()
            elseif wall.getTile then
                tileName = wall:getTile()
            elseif wall.getName then
                tileName = wall:getName()
            end
            
            table.insert(walls, {
                square = sq,
                x = x,
                y = y,
                z = z,
                wall = wall,
                tileName = tileName
            })
        end
    end
    
    return walls
end

-- Get all wall tiles from the room
function ZSRoom:getWallsDoors()
    if not self:isValid() then return {} end
    local walls = {}; for _, w in ipairs(self:getWallsDoorsNS()) do table.insert(walls, w) end; for _, w in ipairs(self:getWallsDoorsEW()) do table.insert(walls, w) end; return walls
end

-- Get all N/S wall tiles from the room
function ZSRoom:getWallsDoorsNS()
    if not self:isValid() then return {} end
    local walls = {}; for _, w in ipairs(self:getWallsDoorsN()) do w.direction = "north"; table.insert(walls, w) end; for _, w in ipairs(self:getWallsDoorsS()) do w.direction = "south"; table.insert(walls, w) end; return walls
end

-- Get all E/W wall tiles from the room
function ZSRoom:getWallsDoorsEW()
    if not self:isValid() then return {} end
    local walls = {}; for _, w in ipairs(self:getWallsDoorsW()) do w.direction = "west"; table.insert(walls, w) end; for _, w in ipairs(self:getWallsDoorsE()) do w.direction = "east"; table.insert(walls, w) end; return walls
end

-- Validate collected walls against airtight wall sets
function ZSRoom:validate()
    if not self:isValid() then
        return {
            valid = false,
            error = "Room is not valid"
        }
    end

    self.minX = nil
    self.maxX = nil
    self.minY = nil
    self.maxY = nil
    self.minZ = nil
    self.maxZ = nil

    local totalCount = 0
    for _ in pairs(self.squares) do
        totalCount = totalCount + 1
    end
    
    local result = {
        squares = {
            total = totalCount,
            withFloor = 0,
            withRoof = 0,
        }
    }

    -- Check if all squares have both floor and roof, calculate min/max X/Y
    for _, sq in pairs(self.squares) do
        if sq then
            local x, y, z = sq:getX(), sq:getY(), sq:getZ()

            if not self.minX or x < self.minX then
                self.minX = x
            end
            if not self.maxX or x > self.maxX then
                self.maxX = x
            end
            if not self.minY or y < self.minY then
                self.minY = y
            end
            if not self.maxY or y > self.maxY then
                self.maxY = y
            end
            if not self.minZ or z < self.minZ then
                self.minZ = z
            end
            if not self.maxZ or z > self.maxZ then
                self.maxZ = z
            end

            if sq:getFloor() then
                result.squares.withFloor = result.squares.withFloor + 1
            end
            local roofSq = getSquare(x, y, z + 1)
            if roofSq and roofSq:getFloor() then
                result.squares.withRoof = result.squares.withRoof + 1
            end
        end
    end

    self.width = self.maxX - self.minX + 1
    self.height = self.maxY - self.minY + 1

    if self.width > 0 and self.height > 0 then
        self.center = {
            x = self.minX + (self.width / 2),
            y = self.minY + (self.height / 2),
            z = self.minZ
        }
    end
    
    local nsWalls = self:getWallsDoorsNS()
    local ewWalls = self:getWallsDoorsEW()
    
    result.nsWalls = {
            total = #nsWalls,
            airtight = 0,
            tiles = {}
        }

    result.ewWalls = {
            total = #ewWalls,
            airtight = 0,
            tiles = {}
        }
    
    -- Use lookup tables for faster checking (O(1) instead of O(n))
    local airtightNS = ZSpaceship.MapData.AIRTIGHT_WALLS_NS_LOOKUP or {}
    local airtightEW = ZSpaceship.MapData.AIRTIGHT_WALLS_EW_LOOKUP or {}
    local airtightDoorsNS = ZSpaceship.MapData.AIRTIGHT_DOORS_NS_LOOKUP or {}
    local airtightDoorsEW = ZSpaceship.MapData.AIRTIGHT_DOORS_EW_LOOKUP or {}
    
    -- Validate N/S walls
    for _, wallData in ipairs(nsWalls) do
        local tileName = wallData.tileName
        -- Check both wall and door lookup tables
        local isAirtight = tileName and (airtightNS[tileName] == true or airtightDoorsNS[tileName] == true)

        table.insert(result.nsWalls.tiles, {
            x = wallData.x,
            y = wallData.y,
            z = wallData.z,
            direction = wallData.direction,
            tileName = tileName,
            airtight = isAirtight
        })
        
        if isAirtight then
            result.nsWalls.airtight = result.nsWalls.airtight + 1
        end
    end
    
    -- Validate E/W walls
    for _, wallData in ipairs(ewWalls) do
        local tileName = wallData.tileName
        -- Check both wall and door lookup tables
        local isAirtight = tileName and (airtightEW[tileName] == true or airtightDoorsEW[tileName] == true)
        
        table.insert(result.ewWalls.tiles, {
            x = wallData.x,
            y = wallData.y,
            z = wallData.z,
            direction = wallData.direction,
            tileName = tileName,
            airtight = isAirtight
        })
        
        if isAirtight then
            result.ewWalls.airtight = result.ewWalls.airtight + 1
        end
    end
    
    -- Overall validation: all walls must be airtight
    result.allAirtight = 
        result.squares.total > 0 and result.squares.total == result.squares.withFloor and result.squares.total == result.squares.withRoof and
        result.nsWalls.total > 0 and result.nsWalls.total == result.nsWalls.airtight and
        result.ewWalls.total > 0 and result.ewWalls.total == result.ewWalls.airtight and
        self.width > 0 and self.width * 2 == result.nsWalls.total and
        self.height > 0 and self.height * 2 == result.ewWalls.total
    
    return result
end

-- Get all non-airtight wall tiles
function ZSRoom:getNonAirtightTiles()
    if not self:isValid() then return {} end
    local walls = self:getWallsDoors()
    local nonAirtightTiles = {}
    local airtightNS = ZSpaceship.MapData.AIRTIGHT_WALLS_NS_LOOKUP or {}
    local airtightEW = ZSpaceship.MapData.AIRTIGHT_WALLS_EW_LOOKUP or {}
    local airtightDoorsNS = ZSpaceship.MapData.AIRTIGHT_DOORS_NS_LOOKUP or {}
    local airtightDoorsEW = ZSpaceship.MapData.AIRTIGHT_DOORS_EW_LOOKUP or {}
    for _, wallData in ipairs(walls) do
        local tileName = wallData.tileName
        local dir = wallData.direction
        local isNS = (dir == "north" or dir == "south")
        local isAirtight = tileName and (isNS and (airtightNS[tileName] == true or airtightDoorsNS[tileName] == true) or (airtightEW[tileName] == true or airtightDoorsEW[tileName] == true))
        if not isAirtight then
            table.insert(nonAirtightTiles, {
                square = wallData.square,
                x = wallData.x,
                y = wallData.y,
                z = wallData.z,
                wall = wallData.wall,
                tileName = tileName,
                direction = wallData.direction
            })
        end
    end
    return nonAirtightTiles
end

-- Collect all doors from the room (checking all boundary squares)
-- O(n) scan where n is the room perimeter, cached for O(1) subsequent retrievals
function ZSRoom:getDoors()
    if not self:isValid() then return {} end
    
    if self.doors then
        return self.doors
    end
    
    -- O(n) scan: only scans boundary squares (perimeter), each side checks one direction
    local doors = {}
    local seenDoors = {}
    
    -- Each side checks doors using sq:getDoor(bool)
    -- W/N doors: check on current square
    -- E/S doors: check on adjacent square (can't use getE()/getS() as they return null if door is closed)
    local sides = {
        {name = "north", squares = self:getSquaresN(), doorDir = true, checkOnAdj = false},
        {name = "south", squares = self:getSquaresS(), doorDir = true, checkOnAdj = true, dx = 0, dy = 1},
        {name = "east", squares = self:getSquaresE(), doorDir = false, checkOnAdj = true, dx = 1, dy = 0},
        {name = "west", squares = self:getSquaresW(), doorDir = false, checkOnAdj = false}
    }
    
    for _, sideInfo in ipairs(sides) do
        for _, sq in ipairs(sideInfo.squares) do
            local isoDoor = nil
            local adjSq = nil
            
            if sideInfo.checkOnAdj then
                -- For E/S: get adjacent square using coordinates and check door there
                if getSquare and sq then
                    local x, y, z = sq:getX(), sq:getY(), sq:getZ()
                    adjSq = getSquare(x + sideInfo.dx, y + sideInfo.dy, z)
                    if adjSq and adjSq.getDoor then
                        isoDoor = adjSq:getDoor(sideInfo.doorDir)
                    end
                end
            else
                -- For W/N: check door on current square
                if sq and sq.getDoor then
                    isoDoor = sq:getDoor(sideInfo.doorDir)
                    -- Get adjacent square for metadata
                    if getSquare then
                        local x, y, z = sq:getX(), sq:getY(), sq:getZ()
                        if sideInfo.name == "north" then
                            adjSq = getSquare(x, y - 1, z)
                        elseif sideInfo.name == "west" then
                            adjSq = getSquare(x - 1, y, z)
                        end
                    end
                end
            end
            
            if isoDoor then
                local doorKey = tostring(isoDoor)
                if not seenDoors[doorKey] then
                    seenDoors[doorKey] = true
                    local x, y, z = sq:getX(), sq:getY(), sq:getZ()
                    local adjX, adjY = adjSq and adjSq:getX() or (x + (sideInfo.dx or 0)), adjSq and adjSq:getY() or (y + (sideInfo.dy or 0))
                    local adjRoom = adjSq and adjSq:getRoom() or nil
                    
                    local doorTileName = nil
                    if isoDoor.getSpriteName then doorTileName = isoDoor:getSpriteName() elseif isoDoor.getTile then doorTileName = isoDoor:getTile() elseif isoDoor.getName then doorTileName = isoDoor:getName() end

                    local isOpen = false
                    if isoDoor.IsOpen then isOpen = isoDoor:IsOpen() end

                    local isExterior = false
                    if isoDoor.isExterior then isExterior = isoDoor:isExterior() end

                    table.insert(doors, {
                        isoDoor = isoDoor,
                        square = sq,
                        adjSquare = adjSq,
                        x = x,
                        y = y,
                        z = z,
                        adjX = adjX,
                        adjY = adjY,
                        direction = sideInfo.name,
                        tileName = doorTileName,
                        isExterior = isExterior,
                        isOpen = isOpen,
                        adjRoom = adjRoom,
                        hasFloor = (adjSq and adjSq.getFloor and adjSq:getFloor() ~= nil),
                        hasRoof = (adjSq and adjSq.getRoof and adjSq:getRoof() ~= nil)
                    })
                end
            end
        end
    end
    
    -- Cache the result for O(1) subsequent retrievals
    self.doors = doors
    self.doorsLastChecked = now
    
    return doors
end

-- Build connections for this room (which rooms it's connected to via doors)
-- Helper: Find adjacent room by checking further in direction
local function findAdjRoom(startSq, direction, currentRoom)
    local dirMap = {north = {0, -1}, south = {0, 1}, east = {1, 0}, west = {-1, 0}}
    local dx, dy = dirMap[direction][1], dirMap[direction][2]
    if not dx or not getSquare then return nil, startSq end
    
    local checkSq = startSq
    for i = 1, 5 do
        local x, y, z = checkSq:getX() + dx, checkSq:getY() + dy, checkSq:getZ()
        local nextSq = getSquare(x, y, z)
        if not nextSq then return nil, checkSq end
        
        local nextRoom = nextSq:getRoom()
        if nextRoom and nextRoom ~= currentRoom then return nextRoom, nextSq end
        if not nextRoom then return nil, nextSq end
        
        checkSq = nextSq
    end
    return nil, startSq
end

-- Helper: Find room by checking adjacent squares
local function findRoomNearSquare(sq, currentRoom)
    if not sq or not getSquare then return nil end
    local dirs = {{0, -1}, {-1, 0}, {0, 1}, {1, 0}}
    for _, dir in ipairs(dirs) do
        local checkSq = getSquare(sq:getX() + dir[1], sq:getY() + dir[2], sq:getZ())
        if checkSq then
            local room = checkSq:getRoom()
            if room and room ~= currentRoom then return room end
        end
    end
    return nil
end

function ZSRoom:buildConnections()
    if not self:isValid() then return end
    
    self.connections = {}
    local doors = self:getDoors()
    if not doors then return end
    
    for _, doorData in ipairs(doors) do
        local door = doorData.isoDoor
        local sq = doorData.square
        local adjSq = doorData.adjSquare
        if door and sq and adjSq then
            local adjRoom = ZSRooms.find(adjSq)
            
            if adjRoom and adjRoom ~= self then
                if not self.connections[adjRoom] then
                    self.connections[adjRoom] = {}
                end
                table.insert(self.connections[adjRoom], {isoDoor = door, square = sq, adjSquare = adjSq, adjRoom = adjRoom})
            end
        end
    end
end

-- Check if room is breached (uses cached vacuum state)
function ZSRoom:isBreached()
    if not self:isValid() or not self.isoRoom then
        return true
    end
    
    -- Return cached vacuum state (calculated by updateAllFast)
    -- If not calculated yet, default to false (sealed)
    return self.vacuumState == ZSRoom.State.BREACHED
end

function ZSRoom:isAllDoorsClosed()
    if not self:isValid() or not self.isoRoom then
        return false
    end
    
    local doors = self:getDoors()
    if not doors then return true end
    
    for _, door in ipairs(doors) do
        if door.isOpen then return false end
    end
    return true
end