class MapCompiler
  module OutputGenerator
    def save_combined_data_lua(out_dir)
      # Output to shared lua folder (relative to map output dir)
      # out_dir is like .../media/maps/ZSpaceship, we want .../media/lua/shared
      base_dir = File.dirname(File.dirname(out_dir))  # Go up from maps/ZSpaceship to media
      lua_dir = File.join(base_dir, "lua", "shared")
      FileUtils.mkdir_p(lua_dir)
      lua_path = File.join(lua_dir, "ZSpaceship_MapData.lua")
      
      # Prepare wall tile data
      ns_wall_tiles = (@wall_tiles_ns - @door_tiles_ns).to_a.sort
      ew_wall_tiles = (@wall_tiles_ew - @door_tiles_ew).to_a.sort
      ns_door_tiles = @door_tiles_ns.to_a.sort
      ew_door_tiles = @door_tiles_ew.to_a.sort
      
      # Generate lookup tables for faster validation
      ns_wall_lookup = ns_wall_tiles.uniq.sort.map { |t| "    [\"#{t}\"] = true" }.join(",\n")
      ew_wall_lookup = ew_wall_tiles.uniq.sort.map { |t| "    [\"#{t}\"] = true" }.join(",\n")
      ns_door_lookup = ns_door_tiles.uniq.sort.map { |t| "    [\"#{t}\"] = true" }.join(",\n")
      ew_door_lookup = ew_door_tiles.uniq.sort.map { |t| "    [\"#{t}\"] = true" }.join(",\n")
      
      lua_content = <<~LUA
        -- Auto-generated by compiler.rb - DO NOT EDIT
        -- Combined map data and wall tiles for ZSpaceship
        
        ZSpaceship = ZSpaceship or {}
        ZSpaceship.MapData = ZSpaceship.MapData or {}
        
        -- Cell coordinates
        ZSpaceship.MapData.CellX = #{@cell_x}
        ZSpaceship.MapData.CellY = #{@cell_y}
      LUA
      
      if !@door_sprites.empty?
        sprites_lua = @door_sprites.to_a.map { |s| "  [\"#{s}\"] = true" }.join(",\n")
        lua_content += <<~LUA
          
          -- Door sprites (first entry from each door definition in YAML)
          ZSpaceship.MapData.DoorSprites = {
          #{sprites_lua}
          }
        LUA
      end
      
      # Initialize Default namespace
      lua_content += <<~LUA
        
        -- Default data (compiled from map YAML)
        ZSpaceship.MapData.Default = ZSpaceship.MapData.Default or {}
      LUA
      
      if !@all_rooms.empty?
        rooms_lua = @all_rooms.map { |room| "  { x = #{room[:x]}, y = #{room[:y]}, z = #{room[:z]}, name = \"#{room[:name]}\" }" }.join(",\n")
        lua_content += <<~LUA
          
          -- Room centers (includes all rooms, including halls)
          ZSpaceship.MapData.Default.Rooms = {
          #{rooms_lua}
          }
        LUA
      end
      
      if !@generators.empty?
        generators_lua = @generators.map { |gen| "  { x = #{gen[:x]}, y = #{gen[:y]}, z = #{gen[:z]} }" }.join(",\n")
        lua_content += <<~LUA
          
          -- Generator coordinates
          ZSpaceship.MapData.Default.Generators = {
          #{generators_lua}
          }
        LUA
      end
      
      # Add wall tiles section
      lua_content += <<~LUA
        
        -- Airtight wall and door tile lookup tables
        -- Lookup tables for faster validation (O(1) instead of O(n))
        -- North/South walls (getWall(true))
        ZSpaceship.MapData.AIRTIGHT_WALLS_NS_LOOKUP = {
        #{ns_wall_lookup}
        }
        
        -- East/West walls (getWall(false))
        ZSpaceship.MapData.AIRTIGHT_WALLS_EW_LOOKUP = {
        #{ew_wall_lookup}
        }
        
        -- Door tiles (North/South direction)
        ZSpaceship.MapData.AIRTIGHT_DOORS_NS_LOOKUP = {
        #{ns_door_lookup}
        }
        
        -- Door tiles (East/West direction)
        ZSpaceship.MapData.AIRTIGHT_DOORS_EW_LOOKUP = {
        #{ew_door_lookup}
        }
      LUA
      
      File.write(lua_path, lua_content)
      puts "Wrote combined map data and wall tiles to #{lua_path}"
    end
    
    def save_spawnpoints_lua(out_dir)
      # Output to maps directory (same as out_dir)
      # out_dir is like .../media/maps/ZSpaceship
      spawnpoints_path = File.join(out_dir, "spawnpoints.lua")
      
      # Generate spawn points for each room center (excluding corridors)
      spawn_points = []
      @room_spawn_points.each do |spawn|
        spawn_points << "                  { posX = #{spawn[:x]}, posY = #{spawn[:y]}, posZ = #{spawn[:z]} }"
      end
      
      spawnpoints_list = spawn_points.join(",\n")
      
      spawnpoints_content = <<~LUA
        -- Auto-generated by compiler.rb - DO NOT EDIT
        function SpawnPoints()
            return {
                unemployed = {
        #{spawnpoints_list}
                }
            }
        end
      LUA
      
      File.write(spawnpoints_path, spawnpoints_content)
      puts "Wrote #{@room_spawn_points.length} spawn points to #{spawnpoints_path}"
    end
  end
end
