class MapCompiler
  module OutputGenerator
    def save_combined_data_lua(out_dir)
      # Output to shared lua folder (relative to map output dir)
      # out_dir is like .../media/maps/ZSpaceship, we want .../media/lua/shared
      base_dir = File.dirname(File.dirname(out_dir))  # Go up from maps/ZSpaceship to media
      lua_dir = File.join(base_dir, "lua", "shared")
      FileUtils.mkdir_p(lua_dir)
      lua_path = File.join(lua_dir, "ZS_MapData.lua")
      
      
      lua_content = <<~LUA
        -- Auto-generated by compiler.rb - DO NOT EDIT
        -- Combined map data and wall tiles for ZSpaceship
        
        ZSpaceship = ZSpaceship or {}
        ZSpaceship.MapData = ZSpaceship.MapData or {}
        
        -- Cell coordinates
        ZSpaceship.MapData.CellX = #{@cell_x}
        ZSpaceship.MapData.CellY = #{@cell_y}
      LUA
      
      
      # Initialize Default namespace
      lua_content += <<~LUA
        
        -- Default data (compiled from map YAML)
        ZSpaceship.MapData.Default = ZSpaceship.MapData.Default or {}
      LUA
      
      if !@all_rooms.empty?
        rooms_lua = @all_rooms.map { |room| "  { x = #{room[:x]}, y = #{room[:y]}, z = #{room[:z]}, name = \"#{room[:name]}\" }" }.join(",\n")
        lua_content += <<~LUA
          
          -- Room centers (includes all rooms, including halls)
          ZSpaceship.MapData.Default.Rooms = {
          #{rooms_lua}
          }
        LUA
      end
      
      if !@locations_by_type.empty?
        locations_sections = @locations_by_type.sort.map do |location_type, coords|
          coords_lua = coords.map { |c| "    { x = #{c[:x]}, y = #{c[:y]}, z = #{c[:z]} }" }.join(",\n")
          "  [\"#{location_type}\"] = {\n#{coords_lua}\n  }"
        end.join(",\n")
        lua_content += <<~LUA
          
          -- Location coordinates (grouped by type)
          ZSpaceship.MapData.Default.Locations = {
          #{locations_sections}
          }
        LUA
      end
      
      
      # Export tiles with flags, grouped by flag
      if !@tiles_with_flags.empty?
        # Group tiles by flag
        tiles_by_flag = {}
        @tiles_with_flags.each do |tile_name, data|
          data[:flags].each do |flag|
            tiles_by_flag[flag] ||= []
            tiles_by_flag[flag] << tile_name
          end
        end
        
        # Generate Lua output grouped by flag (as arrays)
        flag_sections = tiles_by_flag.sort.map do |flag, tile_names|
          tile_list = tile_names.sort.map { |t| "    \"#{t}\"" }.join(",\n")
          "  [\"#{flag}\"] = {\n#{tile_list}\n  }"
        end.join(",\n")
        
        lua_content += <<~LUA
          
          -- Tiles with flags (from tiles: section in YAML), grouped by flag
          ZSpaceship.MapData.Tiles = {
          #{flag_sections}
          }
        LUA
      end
      
      # Generate lookup tables from MapData.Tiles in Lua
      lua_content += <<~LUA
        
        -- Generate door sprites from MapData.Tiles (tiles with DoorN or DoorW flags)
        ZSpaceship.MapData.DoorSprites = {}
        local door_n_tiles = ZSpaceship.MapData.Tiles["DoorN"] or {}
        local door_w_tiles = ZSpaceship.MapData.Tiles["DoorW"] or {}
        for _, tile_name in ipairs(door_n_tiles) do
            ZSpaceship.MapData.DoorSprites[tile_name] = true
        end
        for _, tile_name in ipairs(door_w_tiles) do
            ZSpaceship.MapData.DoorSprites[tile_name] = true
        end
        
        -- Generate airtight wall and door tile lookup tables from MapData.Tiles
        -- Only includes tiles that have both "Airtight" flag and the direction flag
        local airtight_set = {}
        for _, tile_name in ipairs(ZSpaceship.MapData.Tiles["Airtight"]) do
            airtight_set[tile_name] = true
        end
        
        local function buildAirtightLookupTable(direction_flag_list)
            local lookup = {}
            for _, tile_name in ipairs(direction_flag_list) do
                if airtight_set[tile_name] then
                    lookup[tile_name] = true
                end
            end
            return lookup
        end
        
        -- North/South walls (getWall(true)) - from WallN flag, only if also Airtight
        ZSpaceship.MapData.AIRTIGHT_WALLS_NS_LOOKUP = buildAirtightLookupTable(ZSpaceship.MapData.Tiles["WallN"])
        
        -- East/West walls (getWall(false)) - from WallW flag, only if also Airtight
        ZSpaceship.MapData.AIRTIGHT_WALLS_EW_LOOKUP = buildAirtightLookupTable(ZSpaceship.MapData.Tiles["WallW"])
        
        -- Door tiles (North/South direction) - from DoorN flag, only if also Airtight
        ZSpaceship.MapData.AIRTIGHT_DOORS_NS_LOOKUP = buildAirtightLookupTable(ZSpaceship.MapData.Tiles["DoorN"])
        
        -- Door tiles (East/West direction) - from DoorW flag, only if also Airtight
        ZSpaceship.MapData.AIRTIGHT_DOORS_EW_LOOKUP = buildAirtightLookupTable(ZSpaceship.MapData.Tiles["DoorW"])
      LUA
      
      File.write(lua_path, lua_content)
      puts "Wrote combined map data and wall tiles to #{lua_path}"
    end
    
    def save_spawnpoints_lua(out_dir)
      # Output to maps directory (same as out_dir)
      # out_dir is like .../media/maps/ZSpaceship
      spawnpoints_path = File.join(out_dir, "spawnpoints.lua")
      
      # Generate spawn points for each room center (excluding corridors)
      spawn_points = []
      @room_spawn_points.each do |spawn|
        spawn_points << "                  { posX = #{spawn[:x]}, posY = #{spawn[:y]}, posZ = #{spawn[:z]} }"
      end
      
      spawnpoints_list = spawn_points.join(",\n")
      
      spawnpoints_content = <<~LUA
        -- Auto-generated by compiler.rb - DO NOT EDIT
        function SpawnPoints()
            return {
                unemployed = {
        #{spawnpoints_list}
                }
            }
        end
      LUA
      
      File.write(spawnpoints_path, spawnpoints_content)
      puts "Wrote #{@room_spawn_points.length} spawn points to #{spawnpoints_path}"
    end
  end
end
