class MapCompiler
  module OutputGenerator
    def save_combined_data_lua(lua_path)
      FileUtils.mkdir_p(File.dirname(lua_path))
      
      lua_content = <<~LUA
        -- Auto-generated by compiler.rb - DO NOT EDIT
        -- Combined map data and wall tiles for ZSpaceship
        
        ZSpaceship = ZSpaceship or {}
        ZSpaceship.MapData = ZSpaceship.MapData or {}
        
        -- Cell coordinates
        ZSpaceship.MapData.CellX = #{@cell_x}
        ZSpaceship.MapData.CellY = #{@cell_y}
      LUA
      
      
      # Initialize Default namespace
      lua_content += <<~LUA
        
        -- Default data (compiled from map YAML)
        ZSpaceship.MapData.Default = ZSpaceship.MapData.Default or {}
      LUA
      
      if !@all_rooms.empty?
        rooms_lua = @all_rooms.map { |room| "  { x = #{room[:x]}, y = #{room[:y]}, z = #{room[:z]}, name = \"#{room[:name]}\" }" }.join(",\n")
        lua_content += <<~LUA
          
          -- Room centers (includes all rooms, including halls)
          ZSpaceship.MapData.Default.Rooms = {
          #{rooms_lua}
          }
        LUA
      end
      
      if !@locations_by_type.empty?
        locations_sections = @locations_by_type.sort.map do |location_type, coords|
          coords_lua = coords.map { |c| "    { x = #{c[:x]}, y = #{c[:y]}, z = #{c[:z]} }" }.join(",\n")
          "  [\"#{location_type}\"] = {\n#{coords_lua}\n  }"
        end.join(",\n")
        lua_content += <<~LUA
          
          -- Location coordinates (grouped by type)
          ZSpaceship.MapData.Default.Locations = {
          #{locations_sections}
          }
        LUA
      end
      
      
      # Export tiles with flags, grouped by flag
      if !@tiles_with_flags.empty?
        # Group tiles by flag
        tiles_by_flag = {}
        @tiles_with_flags.each do |tile_name, data|
          data[:flags].each do |flag|
            tiles_by_flag[flag] ||= []
            tiles_by_flag[flag] << tile_name
          end
        end
        
        # Generate Lua output grouped by flag (as arrays)
        flag_sections = tiles_by_flag.sort.map do |flag, tile_names|
          tile_list = tile_names.sort.map { |t| "    [\"#{t}\"] = true," }.join("\n")
          "  [\"#{flag}\"] = {\n#{tile_list}\n  }"
        end.join(",\n")
        
        lua_content += <<~LUA
          
          -- Tiles with flags (from tiles: section in YAML), grouped by flag
          ZSpaceship.MapData.Tiles = {
          #{flag_sections}
          }
        LUA
      end
      
      # Generate lookup tables from MapData.Tiles in Lua
      lua_content += <<~LUA
        
        -- Generate door sprites from MapData.Tiles (tiles with DoorN or DoorW flags)
        ZSpaceship.MapData.DoorSprites = {}
        for tile_name in pairs(ZSpaceship.MapData.Tiles.DoorN) do
            ZSpaceship.MapData.DoorSprites[tile_name] = true
        end
        for tile_name in pairs(ZSpaceship.MapData.Tiles.DoorW) do
            ZSpaceship.MapData.DoorSprites[tile_name] = true
        end
        
        local function buildAirtightLookupTable(direction_flag_list)
            local lookup = {}
            for tile_name in pairs(direction_flag_list) do
                if ZSpaceship.MapData.Tiles.Airtight[tile_name] then
                    lookup[tile_name] = true
                end
            end
            return lookup
        end
        
        -- North/South walls (getWall(true)) - from WallN flag, only if also Airtight
        ZSpaceship.MapData.AIRTIGHT_WALLS_NS_LOOKUP = buildAirtightLookupTable(ZSpaceship.MapData.Tiles["WallN"])
        
        -- East/West walls (getWall(false)) - from WallW flag, only if also Airtight
        ZSpaceship.MapData.AIRTIGHT_WALLS_EW_LOOKUP = buildAirtightLookupTable(ZSpaceship.MapData.Tiles["WallW"])
        
        -- Door tiles (North/South direction) - from DoorN flag, only if also Airtight
        ZSpaceship.MapData.AIRTIGHT_DOORS_NS_LOOKUP = buildAirtightLookupTable(ZSpaceship.MapData.Tiles["DoorN"])
        
        -- Door tiles (East/West direction) - from DoorW flag, only if also Airtight
        ZSpaceship.MapData.AIRTIGHT_DOORS_EW_LOOKUP = buildAirtightLookupTable(ZSpaceship.MapData.Tiles["DoorW"])
      LUA
      
      File.write(lua_path, lua_content)
      puts "Wrote combined map data and wall tiles to #{lua_path}"
    end
    
    def save_spawnpoints_lua(out_dir)
      # Output to maps directory (same as out_dir)
      # out_dir is like .../media/maps/ZSpaceship
      spawnpoints_path = File.join(out_dir, "spawnpoints.lua")
      npoints = 0
      
      # Generate spawn points for each room center (excluding corridors)
      lines = []
      lines << "function SpawnPoints()"
      lines << "    return {"
      @spawnpoints.each do |prof_name, points|
        lines << "        #{prof_name} = {"
        points.each do |point|
          lines << "            { posX = #{point[0]}, posY = #{point[1]}, posZ = #{point[2]} },"
          npoints += 1
        end
        lines << "        },"
      end
      lines << "    }"
      lines << "end"
      
      spawnpoints_content = lines.join("\n")
      File.write(spawnpoints_path, spawnpoints_content)
      puts "Wrote #{npoints} spawn points to #{spawnpoints_path}"
    end
  end
end
