-- TODO
--ClothingSelectionDefinitions = ClothingSelectionDefinitions or {}
--
--local outfit = {
--	FullSuitHead = {
--		items = { ZSpaceship.SPACE_SUIT_ID },
--	},
--}
--
--ClothingSelectionDefinitions.astronaut = {
--	Male = outfit,
--	Female = outfit,
--}
