-- Auto-generated by compiler.rb - DO NOT EDIT
-- Map data for ZSpaceship

ZSpaceship = ZSpaceship or {}
ZSpaceship.MapData = ZSpaceship.MapData or {}

-- Cell coordinates
ZSpaceship.MapData.CellX = 78
ZSpaceship.MapData.CellY = 78

-- Door sprites (first entry from each door definition in YAML)
ZSpaceship.MapData.DoorSprites = {
  ["walls_garage_02_60"] = true,
  ["walls_garage_02_57"] = true,
  ["walls_garage_02_52"] = true,
  ["walls_garage_02_49"] = true
}

-- Room centers (includes all rooms, including halls)
ZSpaceship.MapData.DefaultRooms = {
  { x = 20100, y = 20085, z = 10, name = "cockpit" },
  { x = 20096, y = 20089, z = 10, name = "bathroom" },
  { x = 20100, y = 20091, z = 10, name = "longhub" },
  { x = 20104, y = 20089, z = 10, name = "hub" },
  { x = 20096, y = 20093, z = 10, name = "teleport_room" },
  { x = 20104, y = 20093, z = 10, name = "hub" },
  { x = 20089, y = 20097, z = 10, name = "medical" },
  { x = 20096, y = 20097, z = 10, name = "library" },
  { x = 20100, y = 20099, z = 10, name = "longhub" },
  { x = 20104, y = 20097, z = 10, name = "smallR" },
  { x = 20096, y = 20101, z = 10, name = "kitchen" },
  { x = 20104, y = 20101, z = 10, name = "bedroom" },
  { x = 20100, y = 20106, z = 10, name = "energy_storage" },
  { x = 20100, y = 20087, z = 10, name = "hall" },
  { x = 20098, y = 20089, z = 10, name = "hall" },
  { x = 20102, y = 20089, z = 10, name = "hall" },
  { x = 20098, y = 20093, z = 10, name = "hall" },
  { x = 20102, y = 20093, z = 10, name = "hall" },
  { x = 20100, y = 20095, z = 10, name = "hall" },
  { x = 20104, y = 20091, z = 10, name = "hall" },
  { x = 20094, y = 20097, z = 10, name = "hall" },
  { x = 20098, y = 20097, z = 10, name = "hall" },
  { x = 20102, y = 20097, z = 10, name = "hall" },
  { x = 20098, y = 20101, z = 10, name = "hall" },
  { x = 20102, y = 20101, z = 10, name = "hall" },
  { x = 20100, y = 20103, z = 10, name = "hall" }
}
