-- Auto-generated by compiler.rb - DO NOT EDIT
-- Map data for ZSpaceship

ZSpaceship = ZSpaceship or {}
ZSpaceship.MapData = ZSpaceship.MapData or {}

-- Cell coordinates
ZSpaceship.MapData.CellX = 78
ZSpaceship.MapData.CellY = 78

-- Teleporter location (center of teleport room)
ZSpaceship.MapData.TeleporterX = 20095
ZSpaceship.MapData.TeleporterY = 20104
ZSpaceship.MapData.TeleporterZ = 0

-- Door sprites (first entry from each door definition in YAML)
ZSpaceship.MapData.DoorSprites = {
  ["walls_garage_01_49"] = true,
  ["walls_garage_01_52"] = true
}
