ZSpaceship = ZSpaceship or {}
ZSpaceship.MapData = ZSpaceship.MapData or {}

-- Space cell coordinates (from compiled map data)
ZSpaceship.SpaceCellX = ZSpaceship.MapData.CellX or 78
ZSpaceship.SpaceCellY = ZSpaceship.MapData.CellY or 78

-- Cell boundaries (cell is 256x256)
ZSpaceship.SpaceMinX = ZSpaceship.SpaceCellX * 256
ZSpaceship.SpaceMaxX = (ZSpaceship.SpaceCellX + 1) * 256
ZSpaceship.SpaceMinY = ZSpaceship.SpaceCellY * 256
ZSpaceship.SpaceMaxY = (ZSpaceship.SpaceCellY + 1) * 256

-- Unlock a door/garage door object
-- TODO: figure out if the door can be created initially unlocked
local function unlockDoor(obj)
    -- print("Unlocking door: " .. tostring(obj))

    if not obj.getSquare then return end

    local sq = obj:getSquare()
    if not sq or not ZSpaceship.isInSpace(sq) then return end
    
    if obj.setLockedByKey then
        obj:setLockedByKey(false)
    end
    if obj.setLocked then
        obj:setLocked(false)
    end
end

-- Register door unlock handlers for all door sprites (generated by compiler.rb)
-- Only runs once when a new game is started and map is created
local doorUnlockRegistered = false

local function registerDoorUnlocks()
    if doorUnlockRegistered then return end
    if not ZSpaceship.MapData or not ZSpaceship.MapData.DoorSprites then return end
    
    for sprite, _ in pairs(ZSpaceship.MapData.DoorSprites) do
        print("[ZSpaceship] Registering door unlock for: " .. sprite)
        MapObjects.OnNewWithSprite(sprite, unlockDoor, 10)
    end
    
    doorUnlockRegistered = true
end

-- Add communicators to the teleport room container -- now filled via distributions
--local function fillTeleportContainer(obj)
--    if not obj.getSquare then return end
--    
--    local sq = obj:getSquare()
--    if not sq then return end
--    
--    -- Check if in a teleport room
--    local room = sq:getRoom()
--    if not room or not string.find(room:getName(), "teleport") then return end
--    
--    local container = obj:getContainer()
--    if not container then return end
--    
--    -- Only fill if empty (avoid duplicates on reload)
--    if container:getItems():size() >= 5 then return end
--    
--    -- Add 5 space communicators
--    for i = 1, 5 do
--        container:AddItem("ZSpaceship.Communicator_Left")
--    end
--end

-- Initialize water storage with FluidContainer
local function initWaterStorage(obj)
    print("Initializing water storage for: " .. tostring(obj))
    if not obj or not obj.getSquare then return end
    
    local sq = obj:getSquare()
    if not sq or not ZSpaceship.isInSpace(sq) then return end
    
    -- Skip if already has FluidContainer (avoid duplicates on reload)
    if obj:getFluidContainer() then return end
    
    -- Get WaterAmount from sprite properties, fallback to 100
    local waterAmount = 100.0
    if obj:getSprite() and obj:getSprite():getProperties() then
        local props = obj:getSprite():getProperties()
        if props then
            local amountStr = props:get(IsoPropertyType.WaterAmount)
            if amountStr then
                waterAmount = tonumber(amountStr) or 100.0
            end
        end
    end
    
    -- Create and add FluidContainer component
    local fluidContainer = ComponentType.FluidContainer:CreateComponent()
    fluidContainer:setCapacity(waterAmount)
    fluidContainer:addFluid(FluidType.Water, 30.0)
    GameEntityFactory.AddComponent(obj, true, fluidContainer)
    
    -- Sync to clients
    if isServer() then
        obj:sync()
    end
end

-- Remove all animals from the space cell
local function removeAnimalsFromSpace()
    local cell = getCell()
    if not cell then return 0 end

    local removed = 0
    local objects = cell:getObjectList()
    if not objects then return 0 end

    -- Iterate backwards since we're removing
    for i = objects:size() - 1, 0, -1 do
        local obj = objects:get(i)
        if obj and instanceof(obj, "IsoAnimal") and ZSpaceship.isInSpace(obj) then
            obj:removeFromWorld()
            obj:removeFromSquare()
            removed = removed + 1
        end
    end
    return removed
end

-- One-time delayed cleanup: waits for cell to load, removes animals, unregisters itself
local function initialAnimalCleanup()
    local removed = removeAnimalsFromSpace()
    if removed > 0 then
        print("[ZSpaceship] Initial cleanup: removed " .. removed .. " animals from space cell")
    end
    Events.EveryOneMinute.Remove(initialAnimalCleanup)
end

local function squareHasFloor(sq)
    if not sq then return false end
    local floorTiles = ZSpaceship.MapData and ZSpaceship.MapData.Tiles and ZSpaceship.MapData.Tiles["Floor"]
    if not floorTiles then return true end
    local tile = sq:getTileFloor()
    if not tile then return false end
    local name = tile:getName()
    if not name then return false end
    for _, n in ipairs(floorTiles) do
        if n == name then return true end
    end
    return false
end

-- Get ship room bounds from MapData (Default.Rooms or runtime Rooms); z = most frequent z in rooms
local function getShipRoomBounds()
    local rooms = (ZSpaceship.MapData and ZSpaceship.MapData.Rooms) or
        (ZSpaceship.MapData and ZSpaceship.MapData.Default and ZSpaceship.MapData.Default.Rooms)
    if not rooms or #rooms == 0 then return nil end
    local minX, maxX = rooms[1].x, rooms[1].x
    local minY, maxY = rooms[1].y, rooms[1].y
    local zCount = {}
    for i = 1, #rooms do
        local r = rooms[i]
        local z = r.z or 0
        zCount[z] = (zCount[z] or 0) + 1
        if r.x < minX then minX = r.x end
        if r.x > maxX then maxX = r.x end
        if r.y < minY then minY = r.y end
        if r.y > maxY then maxY = r.y end
    end
    local bestZ, bestCount = nil, 0
    for z, count in pairs(zCount) do
        if count > bestCount then bestZ = z; bestCount = count end
    end
    return { minX = minX, maxX = maxX, minY = minY, maxY = maxY, z = bestZ or 0 }
end

--- One-time spawn of N zombies in space suits on the ship.
-- Runs from EveryOneMinute until the space cell is available; then spawns a random
-- count N (between SandboxVars.ZSpaceship.ShipZombieCountMin and ShipZombieCountMax)
-- at random floor positions in ship rooms, using outfit "ZSpaceship_SpaceSuit" (from
-- clothing.xml). Unregisters itself after running once (ZSpaceship.InitialZombiesSpawned).
local function initialShipZombieSpawn()
    if ZSpaceship.InitialZombiesSpawned then
        Events.EveryOneMinute.Remove(initialShipZombieSpawn)
        return
    end
    local cell = getCell()
    if not cell or not cell.getGridSquare then return end
    local bounds = getShipRoomBounds()
    if not bounds then return end
    -- Don't require testSq: spawn even if current cell isn't space cell (game may place when chunk loads)
    local minCount, maxCount = 0, 10
    if SandboxVars and SandboxVars.ZSpaceship then
        local v = SandboxVars.ZSpaceship
        if type(v.ShipZombieCountMin) == "number" then minCount = math.max(0, math.min(100, v.ShipZombieCountMin)) end
        if type(v.ShipZombieCountMax) == "number" then maxCount = math.max(0, math.min(100, v.ShipZombieCountMax)) end
    end
    if minCount > maxCount then minCount, maxCount = maxCount, minCount end
    local N = ZombRand(minCount, maxCount + 1)
    if N == 0 then
        ZSpaceship.InitialZombiesSpawned = true
        Events.EveryOneMinute.Remove(initialShipZombieSpawn)
        return
    end
    local rooms = (ZSpaceship.MapData and ZSpaceship.MapData.Rooms) or
        (ZSpaceship.MapData and ZSpaceship.MapData.Default and ZSpaceship.MapData.Default.Rooms)
    local spawned = 0
    local maxAttempts = N * 5
    for attempt = 1, maxAttempts do
        if spawned >= N then break end
        local x, y
        local useRoomCenter = false
        if rooms and #rooms > 0 then
            local r = rooms[ZombRand(1, #rooms + 1)]
            x = r.x
            y = r.y
            useRoomCenter = true
        else
            x = ZombRand(bounds.minX, bounds.maxX + 1)
            y = ZombRand(bounds.minY, bounds.maxY + 1)
        end
        local sq = cell:getGridSquare(x, y, bounds.z)
        if useRoomCenter or squareHasFloor(sq) then
            local list = addZombiesInOutfit(x, y, bounds.z, 1, "ZSpaceship_SpaceSuit", 50) -- defined in clothing.xml
            if list and list.size and list:size() > 0 then
                spawned = spawned + 1
            end
        end
    end
    ZSpaceship.InitialZombiesSpawned = true
    Events.EveryOneMinute.Remove(initialShipZombieSpawn)
    print("[ZSpaceship] Initial spawn: added " .. spawned .. " zombies in space suits (sandbox count: " .. N .. ")")
end

-- Register on new game start (when map is created)
Events.OnNewGame.Add(function()
    registerDoorUnlocks()

    -- Register all tiles with Storage flag
--    local storage_tiles = ZSpaceship.MapData.Tiles and ZSpaceship.MapData.Tiles["Storage"] or {}
--    for _, tile_name in ipairs(storage_tiles) do
--        MapObjects.OnNewWithSprite(tile_name, fillTeleportContainer, 10)
--    end
    
    -- Register all tiles with WaterStorage flag
    local water_storage_tiles = ZSpaceship.MapData.Tiles and ZSpaceship.MapData.Tiles["WaterStorage"] or {}
    for _, tile_name in ipairs(water_storage_tiles) do
        MapObjects.OnNewWithSprite(tile_name, initWaterStorage, 10)
    end

    -- Delayed animal cleanup (gives time for cell to fully load and animals to spawn)
    Events.EveryOneMinute.Add(initialAnimalCleanup)
    -- Delayed initial zombie spawn in space suits (when space cell is loaded)
    Events.EveryOneMinute.Add(initialShipZombieSpawn)
end)

