ZSpaceship = ZSpaceship or {}
ZSpaceship.MapData = ZSpaceship.MapData or {}

-- Space cell coordinates (from compiled map data)
ZSpaceship.SpaceCellX = ZSpaceship.MapData.CellX or 78
ZSpaceship.SpaceCellY = ZSpaceship.MapData.CellY or 78

-- Cell boundaries (cell is 256x256)
ZSpaceship.SpaceMinX = ZSpaceship.SpaceCellX * 256
ZSpaceship.SpaceMaxX = (ZSpaceship.SpaceCellX + 1) * 256
ZSpaceship.SpaceMinY = ZSpaceship.SpaceCellY * 256
ZSpaceship.SpaceMaxY = (ZSpaceship.SpaceCellY + 1) * 256

-- Unlock a door/garage door object
-- TODO: figure out if the door can be created initially unlocked
local function unlockDoor(obj)
    -- print("Unlocking door: " .. tostring(obj))

    if not obj.getSquare then return end

    local sq = obj:getSquare()
    if not sq or not zsInSpace(sq) then return end
    
    if obj.setLockedByKey then
        obj:setLockedByKey(false)
    end
    if obj.setLocked then
        obj:setLocked(false)
    end
end

-- Register door unlock handlers for all door sprites (generated by compiler.rb)
-- Only runs once when a new game is started and map is created
local doorUnlockRegistered = false

local function registerDoorUnlocks()
    if doorUnlockRegistered then return end
    if not ZSpaceship.MapData or not ZSpaceship.MapData.DoorSprites then return end
    
    for sprite in pairs(ZSpaceship.MapData.DoorSprites) do
        print("[ZSpaceship] Registering door unlock for: " .. sprite)
        MapObjects.OnNewWithSprite(sprite, unlockDoor, 10)
    end
    
    doorUnlockRegistered = true
end

-- Remove all animals from the space cell
local function removeAnimalsFromSpace()
    local cell = getCell()
    if not cell then return 0 end

    local removed = 0
    local objects = cell:getObjectList()
    if not objects then return 0 end

    -- Iterate backwards since we're removing
    for i = objects:size() - 1, 0, -1 do
        local obj = objects:get(i)
        if obj and instanceof(obj, "IsoAnimal") and zsInSpace(obj) then
            obj:removeFromWorld()
            obj:removeFromSquare()
            removed = removed + 1
        end
    end
    return removed
end

-- One-time delayed cleanup: waits for cell to load, removes animals, unregisters itself
local function initialAnimalCleanup()
    local removed = removeAnimalsFromSpace()
    if removed > 0 then
        print("[ZSpaceship] Initial cleanup: removed " .. removed .. " animals from space cell")
    end
    Events.EveryOneMinute.Remove(initialAnimalCleanup)
end

local function squareHasFloor(sq)
    if not sq then return false end
    local floorTiles = ZSpaceship.MapData and ZSpaceship.MapData.Tiles and ZSpaceship.MapData.Tiles["Floor"]
    if not floorTiles then return true end
    local tile = sq:getTileFloor()
    if not tile then return false end
    local name = tile:getName()
    if not name then return false end

    return floorTiles[name] ~= nil
end

-- Get ship room bounds from MapData (Default.Rooms or runtime Rooms); z = most frequent z in rooms
local function getShipRoomBounds()
    local rooms = (ZSpaceship.MapData and ZSpaceship.MapData.Rooms) or
        (ZSpaceship.MapData and ZSpaceship.MapData.Default and ZSpaceship.MapData.Default.Rooms)
    if not rooms or #rooms == 0 then return nil end
    local minX, maxX = rooms[1].x, rooms[1].x
    local minY, maxY = rooms[1].y, rooms[1].y
    local zCount = {}
    for i = 1, #rooms do
        local r = rooms[i]
        local z = r.z or 0
        zCount[z] = (zCount[z] or 0) + 1
        if r.x < minX then minX = r.x end
        if r.x > maxX then maxX = r.x end
        if r.y < minY then minY = r.y end
        if r.y > maxY then maxY = r.y end
    end
    local bestZ, bestCount = nil, 0
    for z, count in pairs(zCount) do
        if count > bestCount then bestZ = z; bestCount = count end
    end
    return { minX = minX, maxX = maxX, minY = minY, maxY = maxY, z = bestZ or 0 }
end

--- One-time spawn of N zombies in space suits on the ship.
-- Runs from EveryOneMinute until the space cell is available; then spawns a random
-- count N (between SandboxVars.ZSpaceship.ShipZombieCountMin and ShipZombieCountMax)
-- at random floor positions in ship rooms, using outfit "ZSpaceship_SpaceSuit" (from
-- clothing.xml). Unregisters itself after running once (ZSpaceship.InitialZombiesSpawned).
local function initialShipZombieSpawn()
    if ZSpaceship.InitialZombiesSpawned then
        Events.EveryOneMinute.Remove(initialShipZombieSpawn)
        return
    end
    local cell = getCell()
    if not cell or not cell.getGridSquare then return end
    local bounds = getShipRoomBounds()
    if not bounds then return end
    -- Don't require testSq: spawn even if current cell isn't space cell (game may place when chunk loads)
    local minCount, maxCount = 0, 10
    if SandboxVars and SandboxVars.ZSpaceship then
        local v = SandboxVars.ZSpaceship
        if type(v.ShipZombieCountMin) == "number" then minCount = math.max(0, math.min(100, v.ShipZombieCountMin)) end
        if type(v.ShipZombieCountMax) == "number" then maxCount = math.max(0, math.min(100, v.ShipZombieCountMax)) end
    end
    if minCount > maxCount then minCount, maxCount = maxCount, minCount end
    local N = ZombRand(minCount, maxCount + 1)
    if N == 0 then
        ZSpaceship.InitialZombiesSpawned = true
        Events.EveryOneMinute.Remove(initialShipZombieSpawn)
        return
    end
    local rooms = (ZSpaceship.MapData and ZSpaceship.MapData.Rooms) or
        (ZSpaceship.MapData and ZSpaceship.MapData.Default and ZSpaceship.MapData.Default.Rooms)
    local spawned = 0
    local maxAttempts = N * 5
    for attempt = 1, maxAttempts do
        if spawned >= N then break end
        local x, y
        local useRoomCenter = false
        if rooms and #rooms > 0 then
            local r = rooms[ZombRand(1, #rooms + 1)]
            x = r.x
            y = r.y
            useRoomCenter = true
        else
            x = ZombRand(bounds.minX, bounds.maxX + 1)
            y = ZombRand(bounds.minY, bounds.maxY + 1)
        end
        local sq = cell:getGridSquare(x, y, bounds.z)
        if useRoomCenter or squareHasFloor(sq) then
            local list = addZombiesInOutfit(x, y, bounds.z, 1, ZSpaceship.ZOMBIE_OUTFIT_ID, 50)
            if list and list.size and list:size() > 0 then
                spawned = spawned + 1
            end
        end
    end
    ZSpaceship.InitialZombiesSpawned = true
    Events.EveryOneMinute.Remove(initialShipZombieSpawn)
    print("[ZSpaceship] Initial spawn: added " .. spawned .. " space zombies (sandbox count: " .. N .. ")")
end

-- Find any crate container in room 'zs_teleport_room' (spaceship teleporter room).
local function findTeleportRoomCrateContainer()
    -- ZSRooms.find("zs_teleport_room") returns cached ZSRoom with precomputed squares.
    local zsRoom = ZSRooms.find("zs_teleport_room")
    if not zsRoom or not zsRoom.squares then return nil end

    for _, sq in ipairs(zsRoom:getSquares()) do
        if sq and sq.getObjects then
            local objects = sq:getObjects()
            if objects then
                for k = 0, objects:size() - 1 do
                    local obj = objects:get(k)
                    if obj and obj.getContainer then
                        local cont = obj:getContainer()
                        if cont and cont:getType() == "crate" then
                            return cont
                        end
                    end
                end
            end
        end
    end

    return nil
end

-- Beam buffer storage (persists via ModData).
local function getBeamBuffer()
    if not ModData or not ModData.getOrCreate then return nil end
    local md = ModData.getOrCreate("ZS_BeamBuffer")
    md.items = md.items or {}
    return md.items
end

local function bufferItem(item)
    local buf = getBeamBuffer()
    if not buf or not item or not item.getFullType then return end
    table.insert(buf, {
        fullType = item:getFullType(),
    })
end

local function flushBeamBuffer(targetCont)
    local buf = getBeamBuffer()
    if not buf or not targetCont then return end

    for _, rec in ipairs(buf) do
        if rec.fullType then
            local newItem = instanceItem and instanceItem(rec.fullType) or nil
            if newItem then
                targetCont:AddItem(newItem)
            end
        end
    end

    for i = #buf, 1, -1 do
        buf[i] = nil
    end
end

function ZSpaceship.flushBeamBufferToShip()
    local targetCont = findTeleportRoomCrateContainer()
    if not targetCont then return end
    flushBeamBuffer(targetCont)
end

-- Server-side helper: beam a single item to the spaceship teleporter-room crate.
-- Returns true on success, false on failure.
function ZSpaceship.beamItemToShip(player, item)
    if not player or not item then return false end

    -- Require Science level >= 3.
    if Perks and Perks.Science and player.getPerkLevel then
        if player:getPerkLevel(Perks.Science) < 3 then
            if player.Say then
                player:Say(getText("UI_ZS_ScienceRequired", 3))
            end
            return false
        end
    end

    local targetCont = findTeleportRoomCrateContainer()
    if not targetCont then
        -- Teleporter room not loaded yet: buffer the item for later delivery.
        bufferItem(item)

        -- Remove item from its current location now, so it effectively leaves the player/world.
        local srcCont = item.getContainer and item:getContainer() or nil
        if srcCont and srcCont.DoRemoveItem then
            srcCont:DoRemoveItem(item)
        else
            local worldItem = item.getWorldItem and item:getWorldItem() or nil
            if worldItem and worldItem.getSquare then
                local sq = worldItem:getSquare()
                if sq and sq.transmitRemoveItemFromSquare then
                    sq:transmitRemoveItemFromSquare(worldItem)
                end
            end
        end

        return true
    end

    -- If crate is available, first flush any buffered items into it.
    flushBeamBuffer(targetCont)

    -- Remove this item from its current location (inventory/container or world).
    local srcCont = item.getContainer and item:getContainer() or nil
    if srcCont and srcCont.DoRemoveItem then
        srcCont:DoRemoveItem(item)
    else
        local worldItem = item.getWorldItem and item:getWorldItem() or nil
        if worldItem and worldItem.getSquare then
            local sq = worldItem:getSquare()
            if sq and sq.transmitRemoveItemFromSquare then
                sq:transmitRemoveItemFromSquare(worldItem)
            end
        end
    end

    targetCont:AddItem(item)

    return true
end

Events.OnNewGame.Add(function()
    if not ZSpaceship.isInitialNewGame("Server") then return end

    registerDoorUnlocks()

    -- Delayed animal cleanup (gives time for cell to fully load and animals to spawn)
    Events.EveryOneMinute.Add(initialAnimalCleanup)
    -- Delayed initial zombie spawn in space suits (when space cell is loaded)
    Events.EveryOneMinute.Add(initialShipZombieSpawn)
end)

Events.OnFillContainer.Add(function(a, b, container)
    -- Zombie	            ZSpaceship_SpaceSuit	ItemContainer:[type:inventorymale, parent:IsoDeadBody{  Name:null,  ID:68,  wasZombie:true,  deathTime:2.087947 }]
    if a == "Zombie" and b == ZSpaceship.ZOMBIE_OUTFIT_ID then
        print("[ZSpaceship] Filling container for space zombie: " .. tostring(container))
        container:AddItem("ZSpaceship.Communicator_Left")
        local suit = container:getItemFromTag(ZSpaceship.Tags.SpaceSuit, false, true)
        if suit and suit.setTankType and suit.setUsedDelta then
            -- add oxygen tank
            suit:setTankType("Base.Oxygen_Tank")
            suit:setUsedDelta(ZombRandFloat(0,1))
        end
        return
    end

    local room_name, container_type = a, b

    -- zs_energy_storage	crate	                ItemContainer:[type:crate, parent:null:zspaceship_0:zspaceship_0:zombie.iso.IsoObject@3696d8eb]
    if room_name == "zs_energy_storage" and container_type == "crate" then
        container:AddItem("ZSpaceship.PowerStorageUnit_Schematic")
        container:AddItem("ZSpaceship.SolarPanel_Schematic")
        return
    end

    if room_name == "medical" and ZS_Utils.isShredder(container) then
        container:removeAllItems()
        if container.setCustomName then
            container:setCustomName(getText("UI_ZS_Shredder")) -- XXX TODO: check in MP
        end
        return
    end
end)

-- Find an InventoryItem by ID, optionally scoped to a specific square table; falls back to near player.
local function findItemById(player, itemID, square)
    if not player or not itemID or not square then return nil end

    local function searchSquare(sq)
        if not sq then return nil end

        -- World inventory objects on the square
        local worldObjs = sq.getWorldObjects and sq:getWorldObjects()
        if worldObjs then
            for i = 0, worldObjs:size() - 1 do
                local wo = worldObjs:get(i)
                if wo and wo.getItem then
                    local it = wo:getItem()
                    if it and it.getID and it:getID() == itemID then
                        return it
                    end
                end
            end
        end

        -- Items inside containers on the square (e.g. corpses, crates, movables)
        local objects = sq.getObjects and sq:getObjects()
        if objects then
            for i = 0, objects:size() - 1 do
                local obj = objects:get(i)
                if obj and obj.getContainer then
                    local cont = obj:getContainer()
                    if cont and cont.getItems then
                        local items = cont:getItems()
                        if items then
                            for j = 0, items:size() - 1 do
                                local it = items:get(j)
                                if it and it.getID and it:getID() == itemID then
                                    return it
                                end
                            end
                        end
                    end
                end
            end
        end

        return nil
    end

    local found = searchSquare(square)
    if found then return found end

    -- Fallback: player inventory
    local inv = player:getInventory()
    if inv and inv.getItemById then
        local item = inv:getItemById(itemID)
        if item then return item end
    end

    return nil
end

-- Handle client commands (MP/SP): beam items to the ship's teleporter-room crate.
Events.OnClientCommand.Add(function(module, command, player, args)
    if module ~= "ZSpaceship" then return end

    if command == "BeamItemToShip" then
        if not player or not args or not args.itemID then return end

        local item = findItemById(player, args.itemID, ZS_Utils.tableToSquare(args.square))
        if item then
            ZSpaceship.beamItemToShip(player, item)
        else
            print("[ZSpaceship] Failed to find item by ID: " .. serialize(args))
        end
    elseif command == "FlushBeamBuffer" then
        ZSpaceship.flushBeamBufferToShip()
    end
end)

