ZSpaceship = ZSpaceship or {}
ZSpaceship.MapData = ZSpaceship.MapData or {}

-- Space cell coordinates (from compiled map data)
ZSpaceship.SpaceCellX = ZSpaceship.MapData.CellX or 78
ZSpaceship.SpaceCellY = ZSpaceship.MapData.CellY or 78

-- Cell boundaries (cell is 256x256)
ZSpaceship.SpaceMinX = ZSpaceship.SpaceCellX * 256
ZSpaceship.SpaceMaxX = (ZSpaceship.SpaceCellX + 1) * 256
ZSpaceship.SpaceMinY = ZSpaceship.SpaceCellY * 256
ZSpaceship.SpaceMaxY = (ZSpaceship.SpaceCellY + 1) * 256

-- Check if coordinates are in space (full cell)
function ZSpaceship.isInSpace(x, y)
    return x >= ZSpaceship.SpaceMinX and x < ZSpaceship.SpaceMaxX and
           y >= ZSpaceship.SpaceMinY and y < ZSpaceship.SpaceMaxY
end

-- Unlock a door/garage door object
-- TODO: figure out if the door can be created initially unlocked
local function unlockDoor(obj)
    -- print("Unlocking door: " .. tostring(obj))

    if not obj.getSquare then return end

    local sq = obj:getSquare()
    if not sq or not ZSpaceship.isInSpace(sq:getX(), sq:getY()) then return end
    
    if obj.setLockedByKey then
        obj:setLockedByKey(false)
    end
    if obj.setLocked then
        obj:setLocked(false)
    end
end

-- Register door unlock handlers for all door sprites (generated by compiler.rb)
-- Only runs once when a new game is started and map is created
local doorUnlockRegistered = false

local function registerDoorUnlocks()
    if doorUnlockRegistered then return end
    if not ZSpaceship.MapData or not ZSpaceship.MapData.DoorSprites then return end
    
    for sprite, _ in pairs(ZSpaceship.MapData.DoorSprites) do
        print("[ZSpaceship] Registering door unlock for: " .. sprite)
        MapObjects.OnNewWithSprite(sprite, unlockDoor, 10)
    end
    
    doorUnlockRegistered = true
end

-- Add communicators to the teleport room container
local function fillTeleportContainer(obj)
    if not obj.getSquare then return end
    
    local sq = obj:getSquare()
    if not sq then return end
    
    -- Check if in a teleport room
    local room = sq:getRoom()
    if not room or not string.find(room:getName(), "teleport") then return end
    
    local container = obj:getContainer()
    if not container then return end
    
    -- Only fill if empty (avoid duplicates on reload)
    if container:getItems():size() >= 5 then return end
    
    -- Add 5 space communicators
    for i = 1, 5 do
        container:AddItem("ZSpaceship.Communicator_Left")
    end
end

-- Register on new game start (when map is created)
Events.OnNewGame.Add(function()
    registerDoorUnlocks()

    -- furniture_storage_02_28 is the chest in teleport room (has container:locker)
    MapObjects.OnNewWithSprite("furniture_storage_02_28", fillTeleportContainer, 10)
end)

-- Hook campfire lightFire to prevent lighting in vacuum
Events.OnGameStart.Add(function()
    if not SCampfireGlobalObject then return end
    
    local originalLightFire = SCampfireGlobalObject.lightFire
    SCampfireGlobalObject.lightFire = function(self)
        local sq = self:getSquare()
        if sq and ZSpaceship.isInSpace(sq:getX(), sq:getY()) then
            local room = sq:getRoom()
            -- No room or room is breached = vacuum = no fire
            if not room then
                return  -- Don't light
            end
        end
        return originalLightFire(self)
    end
end)
