ZSpaceship = ZSpaceship or {}
ZSpaceship.MapData = ZSpaceship.MapData or {}

-- Space cell coordinates (from compiled map data)
ZSpaceship.SpaceCellX = ZSpaceship.MapData.CellX or 78
ZSpaceship.SpaceCellY = ZSpaceship.MapData.CellY or 78

-- Cell boundaries (cell is 256x256)
ZSpaceship.SpaceMinX = ZSpaceship.SpaceCellX * 256
ZSpaceship.SpaceMaxX = (ZSpaceship.SpaceCellX + 1) * 256
ZSpaceship.SpaceMinY = ZSpaceship.SpaceCellY * 256
ZSpaceship.SpaceMaxY = (ZSpaceship.SpaceCellY + 1) * 256

-- Unlock a door/garage door object
-- TODO: figure out if the door can be created initially unlocked
local function unlockDoor(obj)
    -- print("Unlocking door: " .. tostring(obj))

    if not obj.getSquare then return end

    local sq = obj:getSquare()
    if not sq or not ZSpaceship.isInSpace(sq) then return end
    
    if obj.setLockedByKey then
        obj:setLockedByKey(false)
    end
    if obj.setLocked then
        obj:setLocked(false)
    end
end

-- Register door unlock handlers for all door sprites (generated by compiler.rb)
-- Only runs once when a new game is started and map is created
local doorUnlockRegistered = false

local function registerDoorUnlocks()
    if doorUnlockRegistered then return end
    if not ZSpaceship.MapData or not ZSpaceship.MapData.DoorSprites then return end
    
    for sprite, _ in pairs(ZSpaceship.MapData.DoorSprites) do
        print("[ZSpaceship] Registering door unlock for: " .. sprite)
        MapObjects.OnNewWithSprite(sprite, unlockDoor, 10)
    end
    
    doorUnlockRegistered = true
end

-- Add communicators to the teleport room container
local function fillTeleportContainer(obj)
    if not obj.getSquare then return end
    
    local sq = obj:getSquare()
    if not sq then return end
    
    -- Check if in a teleport room
    local room = sq:getRoom()
    if not room or not string.find(room:getName(), "teleport") then return end
    
    local container = obj:getContainer()
    if not container then return end
    
    -- Only fill if empty (avoid duplicates on reload)
    if container:getItems():size() >= 5 then return end
    
    -- Add 5 space communicators
    for i = 1, 5 do
        container:AddItem("ZSpaceship.Communicator_Left")
    end
end

-- Register on new game start (when map is created)
Events.OnNewGame.Add(function()
    registerDoorUnlocks()

    -- furniture_storage_02_28 is the chest in teleport room (has container:locker)
    -- Register all tiles with Storage flag
    local storage_tiles = ZSpaceship.MapData.Tiles and ZSpaceship.MapData.Tiles["Storage"] or {}
    for _, tile_name in ipairs(storage_tiles) do
        MapObjects.OnNewWithSprite(tile_name, fillTeleportContainer, 10)
    end
end)

